# Session 2: Block Codes

In [62]:
# automatically reload channelCodingLib if it is altered and used in the
# notebook
%load_ext autoreload
%autoreload 2
%matplotlib widget

from channelCodingLib import *

import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## 2.1.1

In [75]:
p1 = np.array([1,1,0,1]) #n=4
m1 = 7

p2 = np.array([1,1,1,0,1,1,0,0,1,0,1]) #n=5
m2 = 15

# YOUR CODE HERE
(genmat1,H1) = cyclgenmat(p1,m1, True) #4 rows, 7 columns
(genmat2,H2) = cyclgenmat(p2,m2, True) # 5 rows, 15 columns

(genmat2,H2)

(array([[1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0],
        [0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1],
        [0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0],
        [0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1],
        [0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1]]),
 array([[1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]))

## 2.1.2 & 2.1.3

In [77]:
# YOUR CODE HERE
sys_genmat2 = genmatsys(genmat2)
a = sys_genmat2[:,5:].T
b = np.identity(10,dtype=int)
P = np.concatenate((a,b),axis=1)
P

array([[1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

## 2.1.4

In [94]:
# Information words for testing

X1 = np.array([
    [0, 0, 0, 0], 
    [1, 0, 1, 0]
])

X2 = np.array([
    [0, 0, 0, 0, 0], 
    [0, 0, 0, 0, 1],
    [0, 1, 0, 1, 1]
])

# YOUR CODE HERE
y1 = encoder(genmat1,X1)
print("Y1:\nm",y1)
y2 = encoder(genmat2,X2)
print("Y2:\n",y2)

Y1:
m [[0 0 0 0 0 0 0]
 [1 0 1 0 0 0 1]]
Y2:
 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 1 1 0 0 1 0 1]
 [0 1 0 1 1 1 1 0 0 0 1 0 0 1 1]]


## 2.1.5

In [93]:
# YOUR CODE HERE
codefeatures(genmat1)

TypeError: unsupported operand type(s) for *: 'int' and 'generator'

## 2.1.6

In [95]:
# YOUR CODE HERE
tuple(np.array([
    [0, 0, 0, 0], 
    [1, 0, 1, 0]
]))

(array([0, 0, 0, 0]), array([1, 0, 1, 0]))

## 2.1.7 & 2.1.8

In [ ]:
X1 = np.array([
    [0, 0, 0, 0], 
    [1, 0, 1, 0]
])

X2 = np.array([
    [0, 0, 0, 0, 0], 
    [0, 0, 0, 0, 1],
    [0, 1, 0, 1, 1]
])

# YOUR CODE HERE